module.exports=[
'Hotel Mastic',
'South Shore Resort',
'The Royal Sea Resort',
'The Turkey Shore Resort',
'Wedgewood Resort',
'Land’s End',
'Paradise Point Resort',
'The River Front',
'Four Seasons',
'Giggle Resort',
'The Palazzo',
'Walkabout Beach',
'Alaska’s Island Resort',
'Waikiki Resort',
'ARIA Resort',
'Historic Meadows Motel',
'Queen’s Lion',
'Sunset Plains',
'Secluded Hill',
'Expedition',
'Voyage',
'Ivory Safari',
'Galaxy',
'Ebony Tropic Motel',
'Primal Vista Motel',
'Seacoast Hotel',
'Voyage Resort',
'Prophecy Resort & Spa',
'Opportunity Resort',
'Shoreline Hotel & Spa',
'Rose Thicket Resort',
'Jade Courtyard Hotel',
'Grand Heirloom Resort & Spa',
'Majestic Hotel',
'White Season Resort',
'Jade Bay Resort',
'Antique Palms Resort',
'Parallel Shrine',
'Ebony Market',
'Soft Plains',
'Hardywood Hotel',
'Happy Hotel',
'Happy Stay Hotel',
'The Glory Hotel',
'The Mutiny Hotel',
'The Huntington Hotel',
'Towne Place Suites',
'Cosmopolitan Hotel',
'Eden Roc',
'Coastal bay hotel',
'Dream Connect',
'Purple Orchid',
'The Palazzo Resort',
'The White Rock Hotel',
'The Hot Springs Hotel',
'Venture Hotel',
'The Lakefront',
'The Peninsula',
'The Lakefront',
'Always Welcome',
'Tower Hotel',
'Sunny Canopy',
'Royal Galaxy',
'The Watson Hotel',
'Treebones Resort',
'Waypoint',
'The Eternity Resort',
'Sandy Bloom',



]